from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

import qrcode
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas


CERTIFICATES_FOLDER = Path("certificates")


def generate_certificate(
    device_name: str = "Fake Test Disk",
    serial_number: str = "TEST-DISK-0001",
    total_bytes: int = 10 * 1024 * 1024,
    wipe_method: str = "Single-pass zero overwrite",
    verification_status: str = "PASSED",
) -> dict:
    """Generate a PDF wipe certificate with a QR code."""

    CERTIFICATES_FOLDER.mkdir(
        parents=True,
        exist_ok=True,
    )

    created_at = datetime.now(timezone.utc)

    certificate_number = (
        "DRK-"
        + created_at.strftime("%Y%m%d-%H%M%S")
    )

    certificate_data = {
        "certificate_number": certificate_number,
        "device_name": device_name,
        "serial_number": serial_number,
        "total_bytes": total_bytes,
        "wipe_method": wipe_method,
        "verification_status": verification_status,
        "created_at_utc": created_at.isoformat(),
    }

    canonical_data = json.dumps(
        certificate_data,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")

    certificate_hash = hashlib.sha256(
        canonical_data
    ).hexdigest()

    certificate_data["certificate_hash"] = (
        certificate_hash
    )

    qr_content = json.dumps(
        {
            "certificate_number": certificate_number,
            "verification_status": verification_status,
            "certificate_hash": certificate_hash,
        },
        sort_keys=True,
    )

    qr_image = qrcode.make(qr_content)

    qr_path = CERTIFICATES_FOLDER / (
        f"{certificate_number}_qr.png"
    )

    qr_image.save(qr_path)

    pdf_path = CERTIFICATES_FOLDER / (
        f"{certificate_number}.pdf"
    )

    pdf = canvas.Canvas(
        str(pdf_path),
        pagesize=A4,
    )

    page_width, page_height = A4

    pdf.setTitle(
        f"DataRakshak Certificate {certificate_number}"
    )

    pdf.setFont("Helvetica-Bold", 24)
    pdf.drawCentredString(
        page_width / 2,
        page_height - 35 * mm,
        "DataRakshak",
    )

    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawCentredString(
        page_width / 2,
        page_height - 48 * mm,
        "Secure Data Wipe Certificate",
    )

    pdf.line(
        25 * mm,
        page_height - 55 * mm,
        page_width - 25 * mm,
        page_height - 55 * mm,
    )

    pdf.setFont("Helvetica", 11)

    details = [
        (
            "Certificate Number",
            certificate_number,
        ),
        (
            "Device Name",
            device_name,
        ),
        (
            "Serial Number",
            serial_number,
        ),
        (
            "Storage Size",
            f"{total_bytes} bytes",
        ),
        (
            "Wipe Method",
            wipe_method,
        ),
        (
            "Verification Status",
            verification_status,
        ),
        (
            "Created At",
            created_at.strftime(
                "%Y-%m-%d %H:%M:%S UTC"
            ),
        ),
    ]

    current_y = page_height - 75 * mm

    for label, value in details:
        pdf.setFont("Helvetica-Bold", 11)
        pdf.drawString(
            30 * mm,
            current_y,
            f"{label}:",
        )

        pdf.setFont("Helvetica", 11)
        pdf.drawString(
            75 * mm,
            current_y,
            str(value),
        )

        current_y -= 11 * mm

    pdf.setFont("Helvetica-Bold", 10)
    pdf.drawString(
        30 * mm,
        current_y - 3 * mm,
        "Certificate SHA-256 Hash:",
    )

    pdf.setFont("Helvetica", 8)

    first_half = certificate_hash[:32]
    second_half = certificate_hash[32:]

    pdf.drawString(
        30 * mm,
        current_y - 11 * mm,
        first_half,
    )

    pdf.drawString(
        30 * mm,
        current_y - 17 * mm,
        second_half,
    )

    pdf.drawImage(
        str(qr_path),
        page_width - 65 * mm,
        35 * mm,
        width=40 * mm,
        height=40 * mm,
        preserveAspectRatio=True,
    )

    pdf.setFont("Helvetica", 9)
    pdf.drawString(
        30 * mm,
        30 * mm,
        "Prototype certificate generated by DataRakshak.",
    )

    pdf.drawString(
        30 * mm,
        24 * mm,
        "Current version operates only on the fake test disk.",
    )

    pdf.save()

    return {
        "status": "created",
        "certificate_number": certificate_number,
        "certificate_hash": certificate_hash,
        "pdf_path": str(pdf_path),
        "qr_path": str(qr_path),
    }


if __name__ == "__main__":
    result = generate_certificate()

    print("Certificate created successfully")
    print("Certificate number:", result["certificate_number"])
    print("PDF path:", result["pdf_path"])
    print("QR path:", result["qr_path"])
    print("SHA-256:", result["certificate_hash"])